CREATE TABLE qna (

qQno NUMBER PRIMARY KEY,
qBno NUMBER NOT NULL,
qTitle VARCHAR2(50) NOT NULL,
qWriter VARCHAR2(30) NOT NULL,
qContent VARCHAR2(250) NOT NULL,
qPassword VARCHAR2(60) NOT NULL,
qRegdate DATE DEFAULT SYSDATE,
qUpdatedate DATE DEFAULT SYSDATE,
qReproot NUMBER DEFAULT 0,
qRepstep NUMBER DEFAULT 0,
qRepindent NUMBER DEFAULT 0,
CONSTRAINT fk_qna_qBno FOREIGN KEY(qBno) REFERENCES product(prodBno)
ON DELETE CASCADE

)

CREATE SEQUENCE qna_seq
INCREMENT BY 1
START WITH 1
MAXVALUE 1000000000
NOCYCLE